//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Caută un șir localizat similar cu „Apus”.
        /// </summary>
        internal static string LabelApus {
            get {
                return ResourceManager.GetString("LabelApus", resourceCulture);
            }
        }

        /// <summary>
        ///   Caută un șir localizat similar cu Cauta.
        /// </summary>
        internal static string LabelCauta {
            get {
                return ResourceManager.GetString("LabelCauta", resourceCulture);
            }
        }

        /// <summary>
        ///   Caută un șir localizat similar cu Conditie.
        /// </summary>
        internal static string LabelConditie {
            get {
                return ResourceManager.GetString("LabelConditie", resourceCulture);
            }
        }

        /// <summary>
        ///   Caută un șir localizat similar cu Detalii.
        /// </summary>
        internal static string LabelDetalii {
            get {
                return ResourceManager.GetString("LabelDetalii", resourceCulture);
            }
        }

        /// <summary>
        ///   Caută un șir localizat similar cu Oras.
        /// </summary>
        internal static string LabelOras {
            get {
                return ResourceManager.GetString("LabelOras", resourceCulture);
            }
        }

        /// <summary>
        ///   Caută un șir localizat similar cu „Presiune”.
        /// </summary>
        internal static string LabelPresiune {
            get {
                return ResourceManager.GetString("LabelPresiune", resourceCulture);
            }
        }

        /// <summary>
        ///   Caută un șir localizat similar cu „Răsărit”.
        /// </summary>
        internal static string LabelRasarit {
            get {
                return ResourceManager.GetString("LabelRasarit", resourceCulture);
            }
        }

        /// <summary>
        ///   Caută un șir localizat similar cu „Schimbă Tema”.
        /// </summary>
        internal static string LabelSchimbaTema {
            get {
                return ResourceManager.GetString("LabelSchimbaTema", resourceCulture);
            }
        }

        /// <summary>
        ///   Caută un șir localizat similar cu „Vânt”.
        /// </summary>
        internal static string LabelVant {
            get {
                return ResourceManager.GetString("LabelVant", resourceCulture);
            }
        }

        /// <summary>
        ///   Caută un șir localizat similar cu „Umiditate”.
        /// </summary>
        internal static string LabelUmiditate
        {
            get
            {
                return ResourceManager.GetString("LabelUmiditate", resourceCulture);
            }
        }
    }
}
